### PR TITLE
fix HTTPs problem of direct ajax calls

### PR DESCRIPTION
**Pull request by sodik82**
HTTP ajax calls from content script can't be done from HTTPS page
make HTTP ajax calls from background page instead.

### CODE REVIEW

**Comment by bodyflex** [comment]
seems like a good fix, but it sometimes takes quite some time (10 seconds even) to load the ratings. did you experience similar problems?

**Comment by sodik82** [comment]
hm, I don't believe that this "change" should directly affect speed of HTTP requests (as network and server is usually the slowest part). 
when I played with it little bit (inspecting the background page), normally it executes all request in around one second, but sometimes it takes eg. 4 seconds (but so far I have noticed it is for pages with "same" movie). I can see all requests started but the longest one is about 4 seconds "stalled" but it correspond to http://stackoverflow.com/questions/27513994/chrome-stalls-when-making-multiple-requests-to-same-resource .
However "the first" request is fast as usual. Do you experience same behaviour? Maybe some cache in background page (in order not to ask for same movie 20 times) would help.

**Comment by bodyflex** [comment]
alright, will merge this now, but need to look into that delay if there is anything we could do to compensate for that.

**Comment by sodik82** [comment]
what is your experience about the speed (or slowness)? which pages are the slowest (or is it completely random)?

**Comment by bodyflex** [comment]
yes it seemed to be pretty much random, but never mind. let's hope it works
well most of the time. if anything it should be Chromes fault!

**Pull request merged**
