### PR TITLE
Add Tooltip with poster and full info

### PR DESCRIPTION
**Pull request by dapasier**

### CODE REVIEW

**Comment by bodyflex** [comment]
nice idea, but the images aren't loading with the following error: "Failed to load resource: the server responded with a status of 403 (Forbidden)".

**Comment by dapasier** [comment]
I'm running it on last Opera and last Chrome and it works fine. I don't know why you have this issue.

**Comment by bodyflex** [comment]
we need to ensure it works for every user though so we have to know what is causing this.

**Comment by dapasier** [comment]
Yes, but to be honest with you I don't even have tools for JS and I don't know how to deal with it...

**Comment by bodyflex** [comment]
alright, I will look into it.

**Pull request closed without merging**
